[2023-01-27T05:23:46.374+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: ny_taxi_zones_dag_v2.transform_csv_to_parquet scheduled__2023-01-27T05:23:33.295853+00:00 [queued]>
[2023-01-27T05:23:46.382+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: ny_taxi_zones_dag_v2.transform_csv_to_parquet scheduled__2023-01-27T05:23:33.295853+00:00 [queued]>
[2023-01-27T05:23:46.382+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-27T05:23:46.382+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-01-27T05:23:46.382+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-27T05:23:46.395+0000] {taskinstance.py:1300} INFO - Executing <Task(_PythonDecoratedOperator): transform_csv_to_parquet> on 2023-01-27 05:23:33.295853+00:00
[2023-01-27T05:23:46.400+0000] {standard_task_runner.py:55} INFO - Started process 358 to run task
[2023-01-27T05:23:46.402+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ny_taxi_zones_dag_v2', 'transform_csv_to_parquet', 'scheduled__2023-01-27T05:23:33.295853+00:00', '--job-id', '5867', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag_v1_zones.py', '--cfg-path', '/tmp/tmp56mofzr1']
[2023-01-27T05:23:46.404+0000] {standard_task_runner.py:83} INFO - Job 5867: Subtask transform_csv_to_parquet
[2023-01-27T05:23:46.449+0000] {task_command.py:388} INFO - Running <TaskInstance: ny_taxi_zones_dag_v2.transform_csv_to_parquet scheduled__2023-01-27T05:23:33.295853+00:00 [running]> on host adfcc1cb730b
[2023-01-27T05:23:46.505+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ny_taxi_zones_dag_v2
AIRFLOW_CTX_TASK_ID=transform_csv_to_parquet
AIRFLOW_CTX_EXECUTION_DATE=2023-01-27T05:23:33.295853+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-27T05:23:33.295853+00:00
[2023-01-27T05:23:46.507+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_gcs_dag_v1_zones.py", line 47, in transform_csv_to_parquet
    df = pd.read_csv(src)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 69, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas/_libs/parsers.pyx", line 542, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 642, in pandas._libs.parsers.TextReader._get_header
  File "pandas/_libs/parsers.pyx", line 843, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1917, in pandas._libs.parsers.raise_parser_error
  File "/usr/local/lib/python3.7/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/local/lib/python3.7/gzip.py", line 474, in read
    if not self._read_gzip_header():
  File "/usr/local/lib/python3.7/gzip.py", line 422, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'"L')
[2023-01-27T05:23:46.514+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=ny_taxi_zones_dag_v2, task_id=transform_csv_to_parquet, execution_date=20230127T052333, start_date=20230127T052346, end_date=20230127T052346
[2023-01-27T05:23:46.524+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 5867 for task transform_csv_to_parquet (Not a gzipped file (b'"L'); 358)
[2023-01-27T05:23:46.533+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-27T05:23:46.556+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
