[2023-01-27T04:56:38.732+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: fhv_taxi_data_dag.download_ytd_dataset_from_web scheduled__2022-06-01T00:00:00+00:00 [queued]>
[2023-01-27T04:56:38.751+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: fhv_taxi_data_dag.download_ytd_dataset_from_web scheduled__2022-06-01T00:00:00+00:00 [queued]>
[2023-01-27T04:56:38.751+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-27T04:56:38.751+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-01-27T04:56:38.751+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-27T04:56:38.772+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): download_ytd_dataset_from_web> on 2022-06-01 00:00:00+00:00
[2023-01-27T04:56:38.780+0000] {standard_task_runner.py:55} INFO - Started process 6232 to run task
[2023-01-27T04:56:38.785+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'fhv_taxi_data_dag', 'download_ytd_dataset_from_web', 'scheduled__2022-06-01T00:00:00+00:00', '--job-id', '5668', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag_v1_fhv.py', '--cfg-path', '/tmp/tmphe98vg9e']
[2023-01-27T04:56:38.787+0000] {standard_task_runner.py:83} INFO - Job 5668: Subtask download_ytd_dataset_from_web
[2023-01-27T04:56:38.868+0000] {task_command.py:388} INFO - Running <TaskInstance: fhv_taxi_data_dag.download_ytd_dataset_from_web scheduled__2022-06-01T00:00:00+00:00 [running]> on host 8bc22b99c76b
[2023-01-27T04:56:38.999+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fhv_taxi_data_dag
AIRFLOW_CTX_TASK_ID=download_ytd_dataset_from_web
AIRFLOW_CTX_EXECUTION_DATE=2022-06-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-01T00:00:00+00:00
[2023-01-27T04:56:39.001+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-01-27T04:56:39.002+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'wget https://github.com/DataTalksClub/nyc-tlc-data/releases/download/fhv/yellow_tripdata_2022-06.csv.gz -O /opt/***/yellow_tripdata_2022-06.csv.gz']
[2023-01-27T04:56:39.022+0000] {subprocess.py:86} INFO - Output:
[2023-01-27T04:56:39.028+0000] {subprocess.py:93} INFO - --2023-01-27 04:56:39--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/fhv/yellow_tripdata_2022-06.csv.gz
[2023-01-27T04:56:39.045+0000] {subprocess.py:93} INFO - Resolving github.com (github.com)... 140.82.121.4
[2023-01-27T04:56:39.057+0000] {subprocess.py:93} INFO - Connecting to github.com (github.com)|140.82.121.4|:443... connected.
[2023-01-27T04:56:39.310+0000] {subprocess.py:93} INFO - HTTP request sent, awaiting response... 404 Not Found
[2023-01-27T04:56:39.310+0000] {subprocess.py:93} INFO - 2023-01-27 04:56:39 ERROR 404: Not Found.
[2023-01-27T04:56:39.310+0000] {subprocess.py:93} INFO - 
[2023-01-27T04:56:39.311+0000] {subprocess.py:97} INFO - Command exited with return code 8
[2023-01-27T04:56:39.321+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 8.
[2023-01-27T04:56:39.325+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=fhv_taxi_data_dag, task_id=download_ytd_dataset_from_web, execution_date=20220601T000000, start_date=20230127T045638, end_date=20230127T045639
[2023-01-27T04:56:39.339+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 5668 for task download_ytd_dataset_from_web (Bash command failed. The command returned a non-zero exit code 8.; 6232)
[2023-01-27T04:56:39.357+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-27T04:56:39.389+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
