[2023-01-27T04:56:20.849+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: fhv_taxi_data_dag.download_ytd_dataset_from_web scheduled__2020-07-01T00:00:00+00:00 [queued]>
[2023-01-27T04:56:20.866+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: fhv_taxi_data_dag.download_ytd_dataset_from_web scheduled__2020-07-01T00:00:00+00:00 [queued]>
[2023-01-27T04:56:20.866+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-27T04:56:20.866+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-01-27T04:56:20.866+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-27T04:56:20.889+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): download_ytd_dataset_from_web> on 2020-07-01 00:00:00+00:00
[2023-01-27T04:56:20.905+0000] {standard_task_runner.py:55} INFO - Started process 5792 to run task
[2023-01-27T04:56:20.928+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'fhv_taxi_data_dag', 'download_ytd_dataset_from_web', 'scheduled__2020-07-01T00:00:00+00:00', '--job-id', '5625', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag_v1_fhv.py', '--cfg-path', '/tmp/tmpmsck9z_a']
[2023-01-27T04:56:20.953+0000] {standard_task_runner.py:83} INFO - Job 5625: Subtask download_ytd_dataset_from_web
[2023-01-27T04:56:21.175+0000] {task_command.py:388} INFO - Running <TaskInstance: fhv_taxi_data_dag.download_ytd_dataset_from_web scheduled__2020-07-01T00:00:00+00:00 [running]> on host 8bc22b99c76b
[2023-01-27T04:56:21.477+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fhv_taxi_data_dag
AIRFLOW_CTX_TASK_ID=download_ytd_dataset_from_web
AIRFLOW_CTX_EXECUTION_DATE=2020-07-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-07-01T00:00:00+00:00
[2023-01-27T04:56:21.480+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-01-27T04:56:21.489+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'wget https://github.com/DataTalksClub/nyc-tlc-data/releases/download/fhv/yellow_tripdata_2020-07.csv.gz -O /opt/***/yellow_tripdata_2020-07.csv.gz']
[2023-01-27T04:56:21.549+0000] {subprocess.py:86} INFO - Output:
[2023-01-27T04:56:21.549+0000] {subprocess.py:93} INFO - --2023-01-27 04:56:21--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/fhv/yellow_tripdata_2020-07.csv.gz
[2023-01-27T04:56:21.562+0000] {subprocess.py:93} INFO - Resolving github.com (github.com)... 140.82.121.4
[2023-01-27T04:56:21.574+0000] {subprocess.py:93} INFO - Connecting to github.com (github.com)|140.82.121.4|:443... connected.
[2023-01-27T04:56:21.810+0000] {subprocess.py:93} INFO - HTTP request sent, awaiting response... 404 Not Found
[2023-01-27T04:56:21.811+0000] {subprocess.py:93} INFO - 2023-01-27 04:56:21 ERROR 404: Not Found.
[2023-01-27T04:56:21.811+0000] {subprocess.py:93} INFO - 
[2023-01-27T04:56:21.812+0000] {subprocess.py:97} INFO - Command exited with return code 8
[2023-01-27T04:56:21.846+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 8.
[2023-01-27T04:56:21.853+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=fhv_taxi_data_dag, task_id=download_ytd_dataset_from_web, execution_date=20200701T000000, start_date=20230127T045620, end_date=20230127T045621
[2023-01-27T04:56:21.895+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 5625 for task download_ytd_dataset_from_web (Bash command failed. The command returned a non-zero exit code 8.; 5792)
[2023-01-27T04:56:21.954+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-27T04:56:22.106+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
