[2023-01-27T04:57:28.272+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: fhv_taxi_data_dag_v1.transform_csv_to_parquet scheduled__2020-02-01T00:00:00+00:00 [queued]>
[2023-01-27T04:57:28.289+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: fhv_taxi_data_dag_v1.transform_csv_to_parquet scheduled__2020-02-01T00:00:00+00:00 [queued]>
[2023-01-27T04:57:28.289+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-27T04:57:28.290+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-01-27T04:57:28.290+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-27T04:57:28.315+0000] {taskinstance.py:1300} INFO - Executing <Task(_PythonDecoratedOperator): transform_csv_to_parquet> on 2020-02-01 00:00:00+00:00
[2023-01-27T04:57:28.326+0000] {standard_task_runner.py:55} INFO - Started process 6802 to run task
[2023-01-27T04:57:28.333+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'fhv_taxi_data_dag_v1', 'transform_csv_to_parquet', 'scheduled__2020-02-01T00:00:00+00:00', '--job-id', '5719', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag_v1_fhv.py', '--cfg-path', '/tmp/tmp67bkrsmy']
[2023-01-27T04:57:28.335+0000] {standard_task_runner.py:83} INFO - Job 5719: Subtask transform_csv_to_parquet
[2023-01-27T04:57:28.467+0000] {task_command.py:388} INFO - Running <TaskInstance: fhv_taxi_data_dag_v1.transform_csv_to_parquet scheduled__2020-02-01T00:00:00+00:00 [running]> on host 8bc22b99c76b
[2023-01-27T04:57:28.804+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fhv_taxi_data_dag_v1
AIRFLOW_CTX_TASK_ID=transform_csv_to_parquet
AIRFLOW_CTX_EXECUTION_DATE=2020-02-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-02-01T00:00:00+00:00
[2023-01-27T04:57:28.807+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:192: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  return self.python_callable(*self.op_args, **self.op_kwargs)

[2023-01-27T04:57:31.174+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_gcs_dag_v1_fhv.py", line 60, in transform_csv_to_parquet
    df = pd.read_csv(src, error_bad_lines=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 488, in _read
    return parser.read(nrows)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1047, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 224, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 801, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 857, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 843, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1917, in pandas._libs.parsers.raise_parser_error
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 41721: invalid start byte
[2023-01-27T04:57:31.214+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=fhv_taxi_data_dag_v1, task_id=transform_csv_to_parquet, execution_date=20200201T000000, start_date=20230127T045728, end_date=20230127T045731
[2023-01-27T04:57:31.252+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 5719 for task transform_csv_to_parquet ('utf-8' codec can't decode byte 0xa0 in position 41721: invalid start byte; 6802)
[2023-01-27T04:57:31.304+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-27T04:57:31.406+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
