[2023-01-27T04:59:17.865+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: fhv_taxi_data_dag_v1.download_ytd_dataset_from_web scheduled__2021-12-01T00:00:00+00:00 [queued]>
[2023-01-27T04:59:17.879+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: fhv_taxi_data_dag_v1.download_ytd_dataset_from_web scheduled__2021-12-01T00:00:00+00:00 [queued]>
[2023-01-27T04:59:17.879+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-27T04:59:17.880+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-01-27T04:59:17.880+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-27T04:59:17.899+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): download_ytd_dataset_from_web> on 2021-12-01 00:00:00+00:00
[2023-01-27T04:59:17.908+0000] {standard_task_runner.py:55} INFO - Started process 8172 to run task
[2023-01-27T04:59:17.912+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'fhv_taxi_data_dag_v1', 'download_ytd_dataset_from_web', 'scheduled__2021-12-01T00:00:00+00:00', '--job-id', '5830', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag_v1_fhv.py', '--cfg-path', '/tmp/tmpsn1m0eue']
[2023-01-27T04:59:17.914+0000] {standard_task_runner.py:83} INFO - Job 5830: Subtask download_ytd_dataset_from_web
[2023-01-27T04:59:17.973+0000] {task_command.py:388} INFO - Running <TaskInstance: fhv_taxi_data_dag_v1.download_ytd_dataset_from_web scheduled__2021-12-01T00:00:00+00:00 [running]> on host 8bc22b99c76b
[2023-01-27T04:59:18.056+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fhv_taxi_data_dag_v1
AIRFLOW_CTX_TASK_ID=download_ytd_dataset_from_web
AIRFLOW_CTX_EXECUTION_DATE=2021-12-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-01T00:00:00+00:00
[2023-01-27T04:59:18.057+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-01-27T04:59:18.057+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'wget https://github.com/DataTalksClub/nyc-tlc-data/releases/download/fhv/fhv_tripdata_2021-12.csv.gz -O /opt/***/fhv_tripdata_2021-12.csv.gz']
[2023-01-27T04:59:18.069+0000] {subprocess.py:86} INFO - Output:
[2023-01-27T04:59:18.073+0000] {subprocess.py:93} INFO - --2023-01-27 04:59:18--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/fhv/fhv_tripdata_2021-12.csv.gz
[2023-01-27T04:59:18.090+0000] {subprocess.py:93} INFO - Resolving github.com (github.com)... 140.82.121.3
[2023-01-27T04:59:18.103+0000] {subprocess.py:93} INFO - Connecting to github.com (github.com)|140.82.121.3|:443... connected.
[2023-01-27T04:59:18.343+0000] {subprocess.py:93} INFO - HTTP request sent, awaiting response... 404 Not Found
[2023-01-27T04:59:18.344+0000] {subprocess.py:93} INFO - 2023-01-27 04:59:18 ERROR 404: Not Found.
[2023-01-27T04:59:18.344+0000] {subprocess.py:93} INFO - 
[2023-01-27T04:59:18.344+0000] {subprocess.py:97} INFO - Command exited with return code 8
[2023-01-27T04:59:18.354+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 8.
[2023-01-27T04:59:18.356+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=fhv_taxi_data_dag_v1, task_id=download_ytd_dataset_from_web, execution_date=20211201T000000, start_date=20230127T045917, end_date=20230127T045918
[2023-01-27T04:59:18.367+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 5830 for task download_ytd_dataset_from_web (Bash command failed. The command returned a non-zero exit code 8.; 8172)
[2023-01-27T04:59:18.403+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-27T04:59:18.427+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
