[2023-01-27T04:59:18.123+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: fhv_taxi_data_dag_v1.download_ytd_dataset_from_web scheduled__2022-02-01T00:00:00+00:00 [queued]>
[2023-01-27T04:59:18.132+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: fhv_taxi_data_dag_v1.download_ytd_dataset_from_web scheduled__2022-02-01T00:00:00+00:00 [queued]>
[2023-01-27T04:59:18.132+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-27T04:59:18.132+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-01-27T04:59:18.132+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-27T04:59:18.143+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): download_ytd_dataset_from_web> on 2022-02-01 00:00:00+00:00
[2023-01-27T04:59:18.148+0000] {standard_task_runner.py:55} INFO - Started process 8182 to run task
[2023-01-27T04:59:18.151+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'fhv_taxi_data_dag_v1', 'download_ytd_dataset_from_web', 'scheduled__2022-02-01T00:00:00+00:00', '--job-id', '5832', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag_v1_fhv.py', '--cfg-path', '/tmp/tmpkv5bi2gq']
[2023-01-27T04:59:18.152+0000] {standard_task_runner.py:83} INFO - Job 5832: Subtask download_ytd_dataset_from_web
[2023-01-27T04:59:18.202+0000] {task_command.py:388} INFO - Running <TaskInstance: fhv_taxi_data_dag_v1.download_ytd_dataset_from_web scheduled__2022-02-01T00:00:00+00:00 [running]> on host 8bc22b99c76b
[2023-01-27T04:59:18.287+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fhv_taxi_data_dag_v1
AIRFLOW_CTX_TASK_ID=download_ytd_dataset_from_web
AIRFLOW_CTX_EXECUTION_DATE=2022-02-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-01T00:00:00+00:00
[2023-01-27T04:59:18.288+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-01-27T04:59:18.288+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'wget https://github.com/DataTalksClub/nyc-tlc-data/releases/download/fhv/fhv_tripdata_2022-02.csv.gz -O /opt/***/fhv_tripdata_2022-02.csv.gz']
[2023-01-27T04:59:18.299+0000] {subprocess.py:86} INFO - Output:
[2023-01-27T04:59:18.303+0000] {subprocess.py:93} INFO - --2023-01-27 04:59:18--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/fhv/fhv_tripdata_2022-02.csv.gz
[2023-01-27T04:59:18.315+0000] {subprocess.py:93} INFO - Resolving github.com (github.com)... 140.82.121.3
[2023-01-27T04:59:18.328+0000] {subprocess.py:93} INFO - Connecting to github.com (github.com)|140.82.121.3|:443... connected.
[2023-01-27T04:59:18.585+0000] {subprocess.py:93} INFO - HTTP request sent, awaiting response... 404 Not Found
[2023-01-27T04:59:18.585+0000] {subprocess.py:93} INFO - 2023-01-27 04:59:18 ERROR 404: Not Found.
[2023-01-27T04:59:18.585+0000] {subprocess.py:93} INFO - 
[2023-01-27T04:59:18.585+0000] {subprocess.py:97} INFO - Command exited with return code 8
[2023-01-27T04:59:18.594+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 8.
[2023-01-27T04:59:18.597+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=fhv_taxi_data_dag_v1, task_id=download_ytd_dataset_from_web, execution_date=20220201T000000, start_date=20230127T045918, end_date=20230127T045918
[2023-01-27T04:59:18.608+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 5832 for task download_ytd_dataset_from_web (Bash command failed. The command returned a non-zero exit code 8.; 8182)
[2023-01-27T04:59:18.642+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-27T04:59:18.667+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
